Add methods to get/set log file description and test properties.
ni/niflexlogger-automation-python pull request #29
Opened 2023-04-21 15:22 UTC by peterilbergNI

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/flexlogger-python/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This pull request
- adds methods to get and set the log file description
- adds a method to set several test properties at once
- adds example projects to get and set the log file description
- adds example projects to get and set test properties

### Why should this Pull Request be merged?

Customers have requested methods to get/set the log file description and to set several test properties at once.

### What testing has been done?

I have run added new tests for the new methods. I have run the automated tests and the new example projects.

- [x] I have run the automated tests (required if there are code changes)

2023-04-24 18:36 UTC, chadallee commented
Bump the version to `"FlexLogger 2023 Q2+"` in [README.rst](https://github.com/ni/niflexlogger-automation-python/blob/main/README.rst)

2023-04-24 18:47 UTC, DevinKoopmans requested changes
Looks good aside from the one comment I posted

2023-04-24 22:59 UTC, ccaltagi approved these changes
This should be good to go after the changes requested by Chad and Devin.

2023-04-25 06:21 UTC, peterilbergNI commented on src/flexlogger/automation/_project.py
> +            exception, but instead return a boolean indicating if the project was properly saved.
I don't understand how it came back either. I have removed it again and I've updated the version to 2023 Q2+ as requested by Chad.

2023-04-25 14:46 UTC, chadallee approved these changes

2023-04-25 14:47 UTC, merged